### PR TITLE
Updated .gitignore

### PR DESCRIPTION
**Pull request by flaiming**
Just added some essential ignoring to .gitignore

### CODE REVIEW

**Comment by jsmesami** [comment]
`*.py[cod]` would cover lines 2 and 3, but it is not necessary anyways, because with python 3, all these files are in the `__pycache__` directories, which are already ignored.
`src/naovoce/static` shoud definitely _not_ be ignored, because it contains files that must be versioned. Please note that there is a separate .gitignore in src/naovoce, which covers `cache`, `media` and `components` subdirs.

**Comment by flaiming** [comment]
Sorry, I'm still a bit inexperienced at working with Python3. I find .gitignore in `src/naovoce`, but it doesn't ignore files that will be created in `src/naovoce/static` by `./manage.py collectstatic`. How do you solve this? I usually have `STATIC_ROOT` outside of GIT repository (`../static` for example).

**Comment by jsmesami** [comment]
No problem:) 
During local developement, there is no need to call `collectstatic`, because files are found and served from their project directories. And yes, you can edit your naovoce/settings/local.py to point your STATIC_ROOT eg. to ~/.tmp

**Comment by flaiming** [comment]
Didn't thought of that, but makes sense, I'll do that :)

**Pull request closed without merging**
