### PR TITLE
Barebones

### PR DESCRIPTION
**Pull request by twentyfortysix**
Ahoj,

tady sou posledni zmeny, ktery by se uz vyplatili hodit nekam live at se na to muzem vsichni podivat a osahat si to i na mobilech.  

(Prikladam pro referenci screeny desktop verze a mobilni verze pro pripadny porovnani)
**desktop:**
fruitdetail
add-pin

**mobile:**
gallery
menu
user

filter

dik h

### CODE REVIEW

**Comment by jsmesami** [comment]
@twentyfortysix Neee, tys tam commitnul všechny statiky. Prosím pěkně, dej to pryč...

**Comment by jsmesami** [comment]
Ale jako vypadá to super.

**Comment by twentyfortysix** [comment]
cao
tam ale sou nektery statiky novy a nektery updejtnuty, chces abych nasel ty ktery sem menil a updejtnul jen ty, nebo je tam nechces vubec?
Potazmo, o jakych statikach konkretne mluvis, javascripty,? obrazky? less?...

dik h

**Comment by jsmesami** [comment]
Máš tam commitnuté všechny statiky z appek, jako třeba admin, modeltranslation, rest_framework atd, který ti tam asi nalezly z collectstatic. Collectstatic musíš pustit jenom když ti nastavení STATIC_ROOT ukazuje někam mimo projekt, jinak nemusíš. Smaž prosím všechno, co nepatří do projektu, vč. systémových souborů jako .DS_Store apod.

**Comment by jsmesami** [comment]
BTW můj globální .gitignore:
```
*~
*#
*.bak
*.sw[abcdefghijklmnop]  # vim
.~lock.*

__pycache__/
*.py[cod]
*$py.class

*.class
*.o
*.so

*.log
*.sqlite

.idea
.project
.pydevproject
.settings

.DS_Store
.DS_Store?
.Spotlight-V100
.Trashes
thumbs.db
Thumbs.db
```

**Comment by twentyfortysix** [comment]
cao

hele ja nevim co patri a co nepatri presne do "projektu", commituju co mam.
updejtnul sem .gitignore a ted teda trekuju jen tyhle soubory, je to tak okej?

.bowerrc
.gitignore
API.md
CONTRIBUTING.md
CONTRIBUTORS.md
LICENSE.md
README.md
bower.json
requirements.txt
requirements_devel.txt
setup.py
src/comments/__init__.py
src/comments/admin.py
src/comments/api/__init__.py
src/comments/api/serializers.py
src/comments/forms.py
src/comments/migrations/0001_initial.py
src/comments/migrations/0002_comment_complaint.py
src/comments/migrations/0003_added_indexes.py
src/comments/migrations/__init__.py
src/comments/models.py
src/comments/signals.py
src/comments/utils.py
src/fruit/__init__.py
src/fruit/admin.py
src/fruit/api/__init__.py
src/fruit/api/fields.py
src/fruit/api/serializers.py
src/fruit/api/urls.py
src/fruit/api/views.py
src/fruit/fixtures/kinds.json
src/fruit/forms.py
src/fruit/herbarium/__init__.py
src/fruit/herbarium/api/__init__.py
src/fruit/herbarium/api/serializers.py
src/fruit/herbarium/api/urls.py
src/fruit/herbarium/api/views.py
src/fruit/herbarium/models.py
src/fruit/migrations/0001_initial.py
src/fruit/migrations/0002_fruit_cover_image.py
src/fruit/migrations/0003_added_indexes.py
src/fruit/migrations/0004_add_seasons.py
src/fruit/migrations/0005_fruit_catalogue.py
src/fruit/migrations/__init__.py
src/fruit/models.py
src/fruit/signals.py
src/fruit/templatetags/__init__.py
src/fruit/templatetags/fruit.py
src/fruit/tests/__init__.py
src/fruit/tests/test_api.py
src/fruit/translation.py
src/fruit/urls.py
src/fruit/views.py
src/gallery/__init__.py
src/gallery/admin.py
src/gallery/api/__init__.py
src/gallery/api/fields.py
src/gallery/api/serializers.py
src/gallery/api/urls.py
src/gallery/api/views.py
src/gallery/forms.py
src/gallery/managers.py
src/gallery/migrations/0001_initial.py
src/gallery/migrations/0002_image_author.py
src/gallery/migrations/0003_added_indexes.py
src/gallery/migrations/0004_alter_image_field.py
src/gallery/migrations/__init__.py
src/gallery/models.py
src/gallery/settings.py
src/gallery/signals.py
src/gallery/templatetags/__init__.py
src/gallery/templatetags/thumbs.py
src/gallery/tests/__init__.py
src/gallery/tests/test_api.py
src/gallery/urls.py
src/gallery/utils.py
src/gallery/views.py
src/locale/cs/LC_MESSAGES/django.mo
src/locale/cs/LC_MESSAGES/django.po
src/manage.py
src/naovoce/.gitignore
src/naovoce/__init__.py
src/naovoce/api/__init__.py
src/naovoce/api/urls.py
src/naovoce/api/views.py
src/naovoce/context_processors.py
src/naovoce/fixtures/sites.json
src/naovoce/migrations/0001_initial.py
src/naovoce/migrations/0002_media.py
src/naovoce/migrations/0003_auto_20161108_1627.py
src/naovoce/migrations/__init__.py
src/naovoce/settings/.gitignore
src/naovoce/settings/__init__.py
src/naovoce/settings/base.py
src/naovoce/settings/local_deploy_example.py
src/naovoce/settings/local_devel_example.py
src/naovoce/static/admin/css/base.css
src/naovoce/static/admin/css/changelists.css
src/naovoce/static/admin/css/dashboard.css
src/naovoce/static/admin/css/forms.css
src/naovoce/static/admin/css/ie.css
src/naovoce/static/admin/css/login.css
src/naovoce/static/admin/css/rtl.css
src/naovoce/static/admin/css/widgets.css
src/naovoce/static/admin/fonts/icomoon/Read Me.txt
src/naovoce/static/admin/fonts/icomoon/demo-files/demo.css
src/naovoce/static/admin/fonts/icomoon/demo-files/demo.js
src/naovoce/static/admin/fonts/icomoon/demo.html
src/naovoce/static/admin/fonts/icomoon/fonts/icomoon.eot
src/naovoce/static/admin/fonts/icomoon/fonts/icomoon.svg
src/naovoce/static/admin/fonts/icomoon/fonts/icomoon.ttf
src/naovoce/static/admin/fonts/icomoon/fonts/icomoon.woff
src/naovoce/static/admin/fonts/icomoon/selection.json
src/naovoce/static/admin/fonts/icomoon/style.css
src/naovoce/static/admin/fonts/roboto/roboto.css
src/naovoce/static/admin/fonts/roboto/roboto_bold/Roboto-Bold-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_bold/Roboto-Bold-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_bold/Roboto-Bold-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_bold/Roboto-Bold-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_bold/Roboto-Bold-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_bold/specimen_files/Roboto-Bold-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_bold/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_bold/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_bold/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_bold/stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/Roboto-BoldItalic-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/Roboto-BoldItalic-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/Roboto-BoldItalic-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/Roboto-BoldItalic-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/Roboto-BoldItalic-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/specimen_files/Roboto-BoldItalic-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_bolditalic/stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_italic/Roboto-Italic-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_italic/Roboto-Italic-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_italic/Roboto-Italic-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_italic/Roboto-Italic-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_italic/Roboto-Italic-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_italic/specimen_files/Roboto-Italic-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_italic/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_italic/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_italic/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_italic/stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_light/Roboto-Light-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_light/Roboto-Light-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_light/Roboto-Light-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_light/Roboto-Light-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_light/Roboto-Light-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_light/specimen_files/Roboto-Light-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_light/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_light/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_light/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_light/stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/Roboto-LightItalic-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/Roboto-LightItalic-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/Roboto-LightItalic-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/Roboto-LightItalic-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/Roboto-LightItalic-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/specimen_files/Roboto-LightItalic-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_lightitalic/stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_regular/Roboto-Regular-demo.html
src/naovoce/static/admin/fonts/roboto/roboto_regular/Roboto-Regular-webfont.eot
src/naovoce/static/admin/fonts/roboto/roboto_regular/Roboto-Regular-webfont.svg
src/naovoce/static/admin/fonts/roboto/roboto_regular/Roboto-Regular-webfont.ttf
src/naovoce/static/admin/fonts/roboto/roboto_regular/Roboto-Regular-webfont.woff
src/naovoce/static/admin/fonts/roboto/roboto_regular/specimen_files/Roboto-Regular-cleartype.png
src/naovoce/static/admin/fonts/roboto/roboto_regular/specimen_files/easytabs.js
src/naovoce/static/admin/fonts/roboto/roboto_regular/specimen_files/grid_12-825-55-15.css
src/naovoce/static/admin/fonts/roboto/roboto_regular/specimen_files/specimen_stylesheet.css
src/naovoce/static/admin/fonts/roboto/roboto_regular/stylesheet.css
src/naovoce/static/admin/img/changelist-bg.gif
src/naovoce/static/admin/img/changelist-bg_rtl.gif
src/naovoce/static/admin/img/chooser-bg.gif
src/naovoce/static/admin/img/chooser_stacked-bg.gif
src/naovoce/static/admin/img/default-bg-reverse.gif
src/naovoce/static/admin/img/default-bg.gif
src/naovoce/static/admin/img/deleted-overlay.gif
src/naovoce/static/admin/img/gis/move_vertex_off.png
src/naovoce/static/admin/img/gis/move_vertex_on.png
src/naovoce/static/admin/img/icon-no.gif
src/naovoce/static/admin/img/icon-unknown.gif
src/naovoce/static/admin/img/icon-yes.gif
src/naovoce/static/admin/img/icon_addlink.gif
src/naovoce/static/admin/img/icon_alert.gif
src/naovoce/static/admin/img/icon_calendar.gif
src/naovoce/static/admin/img/icon_changelink.gif
src/naovoce/static/admin/img/icon_clock.gif
src/naovoce/static/admin/img/icon_deletelink.gif
src/naovoce/static/admin/img/icon_error.gif
src/naovoce/static/admin/img/icon_searchbox.png
src/naovoce/static/admin/img/icon_success.gif
src/naovoce/static/admin/img/inline-delete-8bit.png
src/naovoce/static/admin/img/inline-delete.png
src/naovoce/static/admin/img/inline-restore-8bit.png
src/naovoce/static/admin/img/inline-restore.png
src/naovoce/static/admin/img/inline-splitter-bg.gif
src/naovoce/static/admin/img/nav-bg-grabber.gif
src/naovoce/static/admin/img/nav-bg-reverse.gif
src/naovoce/static/admin/img/nav-bg-selected.gif
src/naovoce/static/admin/img/nav-bg.gif
src/naovoce/static/admin/img/selector-icons.gif
src/naovoce/static/admin/img/selector-search.gif
src/naovoce/static/admin/img/sorting-icons.gif
src/naovoce/static/admin/img/tool-left.gif
src/naovoce/static/admin/img/tool-left_over.gif
src/naovoce/static/admin/img/tool-right.gif
src/naovoce/static/admin/img/tool-right_over.gif
src/naovoce/static/admin/img/tooltag-add.gif
src/naovoce/static/admin/img/tooltag-add.png
src/naovoce/static/admin/img/tooltag-add_over.gif
src/naovoce/static/admin/img/tooltag-arrowright.gif
src/naovoce/static/admin/img/tooltag-arrowright.png
src/naovoce/static/admin/img/tooltag-arrowright_over.gif
src/naovoce/static/admin/js/LICENSE-JQUERY.txt
src/naovoce/static/admin/js/SelectBox.js
src/naovoce/static/admin/js/SelectFilter2.js
src/naovoce/static/admin/js/actions.js
src/naovoce/static/admin/js/actions.min.js
src/naovoce/static/admin/js/admin/DateTimeShortcuts.js
src/naovoce/static/admin/js/admin/RelatedObjectLookups.js
src/naovoce/static/admin/js/calendar.js
src/naovoce/static/admin/js/collapse.js
src/naovoce/static/admin/js/collapse.min.js
src/naovoce/static/admin/js/core.js
src/naovoce/static/admin/js/inlines.js
src/naovoce/static/admin/js/inlines.min.js
src/naovoce/static/admin/js/jquery.init.js
src/naovoce/static/admin/js/jquery.js
src/naovoce/static/admin/js/jquery.min.js
src/naovoce/static/admin/js/prepopulate.js
src/naovoce/static/admin/js/prepopulate.min.js
src/naovoce/static/admin/js/related-widget-wrapper.js
src/naovoce/static/admin/js/timeparse.js
src/naovoce/static/admin/js/urlify.js
src/naovoce/static/coffee/donate.coffee
src/naovoce/static/coffee/kinds-filter.coffee
src/naovoce/static/coffee/naovoce.coffee
src/naovoce/static/etc/etica/etica.eot
src/naovoce/static/etc/etica/etica.svg
src/naovoce/static/etc/etica/etica.ttf
src/naovoce/static/etc/etica/etica.woff
src/naovoce/static/etc/fruitfont/fruitfont.eot
src/naovoce/static/etc/fruitfont/fruitfont.svg
src/naovoce/static/etc/fruitfont/fruitfont.ttf
src/naovoce/static/etc/fruitfont/fruitfont.woff
src/naovoce/static/facebook/js/fbconnect.js
src/naovoce/static/img/apple-touch-icon-114x114-precomposed.png
src/naovoce/static/img/apple-touch-icon-120x120-precomposed.png
src/naovoce/static/img/apple-touch-icon-144x144-precomposed.png
src/naovoce/static/img/apple-touch-icon-152x152-precomposed.png
src/naovoce/static/img/apple-touch-icon-72x72-precomposed.png
src/naovoce/static/img/apple-touch-icon-76x76-precomposed.png
src/naovoce/static/img/apple-touch-icon-precomposed.png
src/naovoce/static/img/arrow.svg
src/naovoce/static/img/bg.svg
src/naovoce/static/img/envelope.svg
src/naovoce/static/img/favicon.ico
src/naovoce/static/img/ham.svg
src/naovoce/static/img/holder_01.png
src/naovoce/static/img/holder_02.png
src/naovoce/static/img/holder_03.png
src/naovoce/static/img/inputs_decoration.svg
src/naovoce/static/img/inputs_decoration_inverse.svg
src/naovoce/static/img/kinds.svg
src/naovoce/static/img/locate.svg
src/naovoce/static/img/location.svg
src/naovoce/static/img/na-ovoce.svg
src/naovoce/static/img/search.svg
src/naovoce/static/img/toggle.svg
src/naovoce/static/img/x.svg
src/naovoce/static/less/bootstrap.less
src/naovoce/static/less/clusters.less
src/naovoce/static/less/naovoce.less
src/naovoce/static/less/variables.less
src/naovoce/static/modeltranslation/css/tabbed_translation_fields.css
src/naovoce/static/modeltranslation/js/clearable_inputs.js
src/naovoce/static/modeltranslation/js/force_jquery.js
src/naovoce/static/modeltranslation/js/tabbed_translation_fields.js
src/naovoce/static/rest_framework/css/bootstrap-tweaks.css
src/naovoce/static/rest_framework/css/bootstrap.min.css
src/naovoce/static/rest_framework/css/default.css
src/naovoce/static/rest_framework/css/prettify.css
src/naovoce/static/rest_framework/docs/css/base.css
src/naovoce/static/rest_framework/docs/css/bootstrap-theme.min.css
src/naovoce/static/rest_framework/docs/css/bootstrap.min.css
src/naovoce/static/rest_framework/docs/css/font-awesome-4.0.3.css
src/naovoce/static/rest_framework/docs/css/highlight.css
src/naovoce/static/rest_framework/docs/css/jquery.json-view.min.css
src/naovoce/static/rest_framework/docs/fonts/fontawesome-webfont.eot
src/naovoce/static/rest_framework/docs/fonts/fontawesome-webfont.svg
src/naovoce/static/rest_framework/docs/fonts/fontawesome-webfont.ttf
src/naovoce/static/rest_framework/docs/fonts/fontawesome-webfont.woff
src/naovoce/static/rest_framework/docs/fonts/glyphicons-halflings-regular.eot
src/naovoce/static/rest_framework/docs/fonts/glyphicons-halflings-regular.svg
src/naovoce/static/rest_framework/docs/fonts/glyphicons-halflings-regular.ttf
src/naovoce/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff
src/naovoce/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff2
src/naovoce/static/rest_framework/docs/img/favicon.ico
src/naovoce/static/rest_framework/docs/img/grid.png
src/naovoce/static/rest_framework/docs/js/api.js
src/naovoce/static/rest_framework/docs/js/base.js
src/naovoce/static/rest_framework/docs/js/bootstrap.min.js
src/naovoce/static/rest_framework/docs/js/highlight.pack.js
src/naovoce/static/rest_framework/docs/js/jquery-1.10.2.min.js
src/naovoce/static/rest_framework/docs/js/jquery.json-view.min.js
src/naovoce/static/rest_framework/fonts/glyphicons-halflings-regular.eot
src/naovoce/static/rest_framework/fonts/glyphicons-halflings-regular.svg
src/naovoce/static/rest_framework/fonts/glyphicons-halflings-regular.ttf
src/naovoce/static/rest_framework/fonts/glyphicons-halflings-regular.woff
src/naovoce/static/rest_framework/fonts/glyphicons-halflings-regular.woff2
src/naovoce/static/rest_framework/img/glyphicons-halflings-white.png
src/naovoce/static/rest_framework/img/glyphicons-halflings.png
src/naovoce/static/rest_framework/img/grid.png
src/naovoce/static/rest_framework/js/ajax-form.js
src/naovoce/static/rest_framework/js/bootstrap.min.js
src/naovoce/static/rest_framework/js/coreapi-0.1.0.js
src/naovoce/static/rest_framework/js/csrf.js
src/naovoce/static/rest_framework/js/default.js
src/naovoce/static/rest_framework/js/jquery-1.12.4.min.js
src/naovoce/static/rest_framework/js/prettify-min.js
src/naovoce/templates/404.html
src/naovoce/templates/500.html
src/naovoce/templates/503.html
src/naovoce/templates/_base.html
src/naovoce/templates/account/email/email_confirmation_message.txt
src/naovoce/templates/account/email/email_confirmation_subject.txt
src/naovoce/templates/account/email/password_reset_key_message.txt
src/naovoce/templates/account/email/password_reset_key_subject.txt
src/naovoce/templates/account/email_confirm.html
src/naovoce/templates/account/email_confirmed.html
src/naovoce/templates/account/login.html
src/naovoce/templates/account/logout.html
src/naovoce/templates/account/password_change.html
src/naovoce/templates/account/password_reset.html
src/naovoce/templates/account/password_reset_done.html
src/naovoce/templates/account/password_reset_from_key.html
src/naovoce/templates/account/password_reset_from_key_done.html
src/naovoce/templates/account/password_set.html
src/naovoce/templates/account/signup.html
src/naovoce/templates/account/verification_sent.html
src/naovoce/templates/admin/base_site.html
src/naovoce/templates/base.html
src/naovoce/templates/comments/inc/comments.html
src/naovoce/templates/comments/inc/form.html
src/naovoce/templates/comments/inc/formjs.html
src/naovoce/templates/fruit/add.html
src/naovoce/templates/fruit/delete.html
src/naovoce/templates/fruit/detail.html
src/naovoce/templates/fruit/edit.html
src/naovoce/templates/fruit/inc/fruitform.html
src/naovoce/templates/gallery/browser.html
src/naovoce/templates/gallery/inc/form.html
src/naovoce/templates/gallery/inc/formjs.html
src/naovoce/templates/gallery/inc/link.html
src/naovoce/templates/gallery/inc/lookbook.html
src/naovoce/templates/gallery/inc/thumbs.html
src/naovoce/templates/gallery/index.html
src/naovoce/templates/http_error.html
src/naovoce/templates/inc/confirm.html
src/naovoce/templates/inc/facebookjs.html
src/naovoce/templates/inc/fileinput.html
src/naovoce/templates/inc/mapjs.html
src/naovoce/templates/inc/social.html
src/naovoce/templates/inc/svg/cancel.html
src/naovoce/templates/inc/svg/logo.html
src/naovoce/templates/inc/twitterjs.html
src/naovoce/templates/inc/user_info.html
src/naovoce/templates/map.html
src/naovoce/templates/pickers/avatar.html
src/naovoce/templates/pickers/detail.html
src/naovoce/templates/pickers/messages.html
src/naovoce/templates/pickers/settings.html
src/naovoce/templates/robots.txt
src/naovoce/templates/socialaccount/authentication_error.html
src/naovoce/templates/socialaccount/connections.html
src/naovoce/templates/socialaccount/login_cancelled.html
src/naovoce/templates/socialaccount/signup.html
src/naovoce/templates/staticpage/codex.html
src/naovoce/templates/staticpage/page.html
src/naovoce/tests.py
src/naovoce/urls.py
src/naovoce/views.py
src/naovoce/wsgi.py
src/newsletter/__init__.py
src/newsletter/admin.py
src/newsletter/migrations/0001_initial.py
src/newsletter/migrations/__init__.py
src/newsletter/models.py
src/newsletter/templates/admin/newsletter/campaign/change_form.html
src/newsletter/urls.py
src/newsletter/views.py
src/staticpage/__init__.py
src/staticpage/admin.py
src/staticpage/api/__init__.py
src/staticpage/api/serializers.py
src/staticpage/api/settings.py
src/staticpage/api/urls.py
src/staticpage/api/views.py
src/staticpage/fixtures/staticpages.json
src/staticpage/migrations/0001_initial.py
src/staticpage/migrations/__init__.py
src/staticpage/models.py
src/staticpage/views.py
src/user/__init__.py
src/user/adapters.py
src/user/admin.py
src/user/api/__init__.py
src/user/api/serializers.py
src/user/api/signup/__init__.py
src/user/api/signup/serializers.py
src/user/api/signup/urls.py
src/user/api/signup/views.py
src/user/api/token_auth/__init__.py
src/user/api/token_auth/serializers.py
src/user/api/token_auth/urls.py
src/user/api/token_auth/views.py
src/user/api/urls.py
src/user/api/views.py
src/user/forms.py
src/user/management/__init__.py
src/user/management/commands/__init__.py
src/user/management/commands/dump_emails.py
src/user/migrations/0001_initial.py
src/user/migrations/0002_message.py
src/user/migrations/0003_alter_fields.py
src/user/migrations/0004_auto_20160324_1431.py
src/user/migrations/0005_added_indexes.py
src/user/migrations/0006_alter_avatar_upload_to.py
src/user/migrations/0007_message_context.py
src/user/migrations/0008_add_user_resolution.py
src/user/migrations/0009_fruituser_external_url.py
src/user/migrations/__init__.py
src/user/models.py
src/user/signals.py
src/user/templatetags/__init__.py
src/user/templatetags/avatar.py
src/user/urls.py
src/user/utils.py
src/user/views.py
src/utils/__init__.py
src/utils/api/__init__.py
src/utils/api/fields.py
src/utils/api/permissions.py
src/utils/avatar.py
src/utils/choices.py
src/utils/colors.py
src/utils/coords.py
src/utils/fields.py
src/utils/full_url.py
src/utils/i18n/__init__.py
src/utils/i18n/middleware.py
src/utils/mixins.py
src/utils/models.py
src/utils/templatetags/__init__.py
src/utils/templatetags/choices.py
src/utils/templatetags/coords.py
src/utils/templatetags/full_url.py
src/utils/templatetags/getitem.py
src/utils/templatetags/markup.py
src/utils/templatetags/naturalsort.py
src/utils/templatetags/truncate.py
src/utils/templatetags/typo.py
src/utils/tokenizer.py
src/utils/views.py

**Comment by jsmesami** [comment]
Do projektu patří:
```
src/naovoce/static/coffee/
src/naovoce/static/etc/
src/naovoce/static/img/
src/naovoce/static/less/
```
Do projektu nepatří:
```
src/naovoce/static/admin/
src/naovoce/static/modeltranslation/
src/naovoce/static/rest_framework/
src/naovoce/static/facebook/
```

**Comment by twentyfortysix** [comment]
vyhodil sem odtamtud teda adresare:

src/naovoce/static/admin/
src/naovoce/static/modeltranslation/
src/naovoce/static/rest_framework/
src/naovoce/static/facebook/

podivej se jestli to je uz takhle ok.
dik h

**Pull request merged**
